from __future__ import annotations

from typing import Protocol


class HermesAdapter(Protocol):
    def capabilities(self) -> dict: ...
    def create_run(self, input_text: str, *, idempotency_key: str, **kwargs) -> dict: ...
    def create_demo_run(self, input_text: str, *, idempotency_key: str) -> dict: ...
    def get_run(self, run_id: str) -> dict: ...
    def get_run_events(self, run_id: str): ...
    def resolve_run_approval(self, run_id: str, approve: bool) -> dict: ...
    def stop_run(self, run_id: str) -> dict: ...
